---
title: Working philosophy - page1
author: jml
date: '2020-07-08'
slug: working-philosophy
categories:
  - R
tags:
  - Philosophy
  - Life experience
---

The following note is one of a series on philosophy. The thoughts are prepared by a family elder. 

## Page One

In the pure sense it’s (philosophy) concerned with: 

* Our nature: what we are.
* Our understanding: how we know.

Political theory and aesthetics are subsidiary offshoots.

For the Greeks, the paradigm was Mind + Body + Soul.

1600 watershed moment: coincided with the explosion of scientific discoveries in the West (Royal Societies formed in France and UK). 

Theories of Descartes and Locke.

### Soul
The Church took monopoly control of man’s Soul after 800 and Charlemagne.

Church and State began to operate as a double act. You look after my back : I’ll look after your’s. We’ll both be better off that way!

Soul became progressively out of fashion after 1918. 

Atheists argued “ how could God have licenced the evil of WW1” - and then there was the Holocaust.


### 20 century materialists

Mind= Body and there is nothing else.


### Descartes

Descartes was the first to unpack and present his own developement of Platonic and Aristotelian notions with a look over his shoulder at religion at the same time.

His Meditations are not long.

His famous conclusions ( argued over today):

* je pense donc je suis: i think therefore must exist.

* My mind and my body must be two separate entities

* Although God must be playing a part somewhere because my ideas are “ clear and distinct”

* Ideas consist of a core element and secondary qualities. Eg wax which melts.

* Evil Genius. How do I differentiate between the ideas I have in my dreams and when I’m awake.
